version: '3.4'
services:
  jira:
    image: haxqer/jira:9.15.2
    container_name: jira
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./data/jira:/var/jira
    restart: always
    networks:
      - network-bridge

  mysql:
    image: mysql:8.0
    container_name: mysql-jira
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=jira
      - MYSQL_ROOT_PASSWORD=123394
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=123394
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    ports:
      - "3036:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
