version: '3.7'
services:
  jira:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira
    environment:
      - TZ=Asia/Shanghai
    #      - JVM_MINIMUM_MEMORY=1g
    #      - JVM_MAXIMUM_MEMORY=12g
    #      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - db
    ports:
      - "9900:8080"
    volumes:
      - ./data/jira:/var/jira
#      - ./server.xml:/opt/jira/conf/server.xml
    restart: always

  db:
    image: mysql:8.0
    container_name: jira-db
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=jira
      - MYSQL_ROOT_PASSWORD=123394
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=123394
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin' ]
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
